name: "Snyk Full Scan"
description: "Run Snyk Code, Snyk Security, and Snyk License scans and upload results to Snyk dashboard"

inputs:
  working-directory:
    description: "Directory to scan"
    required: false
    default: "."   
    
  run-code-scan:
    description: "Run Snyk Code (SAST)"
    required: false
    default: "true"

  run-oss-scan:
    description: "Run Snyk Open Source (Security)"
    required: false
    default: "true"

  run-license-scan:
    description: "Run Snyk License scan"
    required: false
    default: "true"

  severity-threshold:
    description: "Fail build if issues >= this severity"
    required: false
    default: "high"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: restore
      run: dotnet restore

    - name: Setup Snyk CLI
      uses: snyk/actions/setup@master

    - name: Snyk Code Scan
      if: ${{ inputs.run-code-scan == 'true' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        snyk code test --severity-threshold=${{ inputs.severity-threshold }}

    - name: Snyk Open Source Security Scan and License Scan
      if: ${{ inputs.run-oss-scan == 'true' }}
      shell: bash
      # working-directory: ${{ inputs.working-directory }}
      run: snyk test --all-projects --severity-threshold=${{ inputs.severity-threshold }}

    - name: Upload results to Snyk Dashboard
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: snyk monitor --all-projects 
